name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Increase Gradle memory
        run: echo "org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties

      - name: Clean Gradle cache
        run: ./gradlew cleanBuildCache

      - name: Clean project
        run: ./gradlew clean

      - name: Build With Gradle
        run: |
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all --stacktrace --info

      - name: Check if APK was built successfully
        id: check_apk
        run: |
          if [ ! -f app/build/outputs/apk/release/*.apk ]; then
            echo "APK not found!"
            exit 1
          fi

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          cp app/build/outputs/apk/release/*.apk ${{ github.workspace }}/apk/

      - name: List files in apk directory (for debugging)
        run: ls -la ${{ github.workspace }}/apk/

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*.apk
